### ISSUE TITLE
seed list from other lists

### ISSUE THREAD

**Issue by uhoreg** [Atreatis/matrix-servers#1]
e.g. https://www.hello-matrix.net/public_servers.php and https://the-federation.info/protocol/matrix (you may want to contact the admins to see if they want to be included)

**Comment by Atreatis** [comment]
Heya, thanks for linking these resources I will definitely get on it as soon as possible :)

**Comment by Atreatis** [comment]
Bookmarked them and processing the information, will have to contact each of the admins before adding them to the list. Because I don't want to have listings added without permissions from the maintainer.
