### ISSUE TITLE
List perthchat please

### ISSUE THREAD

**Issue by PC-Admin** [Atreatis/matrix-servers#2]
Server name: Perth Chat
Domain: https://perthchat.org
Maintainer: @PC-Admin:perthchat.org
Founded: 11-09-2017
Description: Perths oldest public matrix server, currently hosted in Singapore. It has a 25MB file size limit and no google captcha.

**Comment by PC-Admin** [comment]
Actually make the description:

Description: Perths run matrix server, currently hosted in Singapore. It has a 25MB file size limit and no google captcha.

**Comment by Atreatis** [comment]
Added, updated & published 👍
