### ISSUE TITLE
[ADD] beerfactory.org

### ISSUE THREAD

**Issue by njouanin** [Atreatis/matrix-servers#3]
**Server name:**  Beerfactory
**Domain:**  https://beerfactory.org/
**Maintainer:**  @nico:beerfactory.org
**Founded:**  about a year ago
**Web client:**  https://matrix.beerfactory.org/
**Description:** Self hosted public Matrix server.

**Comment by Atreatis** [comment]
Will add it first thing in the morning, currently on the road :thumbsup:

**Comment by Atreatis** [comment]
Server has been added to the list 🍺
