### ISSUE TITLE
[ADD] feneas.org

### ISSUE THREAD

**Issue by jaywink** [Atreatis/matrix-servers#4]
**Server name:**  Federated Networks Association
**Domain:**  feneas.org
**Maintainer:**  Federated Networks Association (support: #feneas:feneas.org room)
**Founded:**  2018
**Web client:**  https://chat.feneas.org
**Description:** Federated Networks Association is a non-profit volunteer organization that aims to spread knowledge about federated web projects and help people and projects involved in this area. The Matrix server we run is funded from the association funds.

**Comment by Atreatis** [comment]
I will be adding the support channel in a separated column later on thanks to your feedback, although I would need to know who's the core maintainer of the server so I can add him / her to the list.

**Comment by jaywink** [comment]
We don't have one since all the things are maintained by an admin team, but I guess you can add me there: `@jaywink:federator.dev`, I'm one of the admins.

**Comment by Atreatis** [comment]
Added to the list now 👍

**Comment by Atreatis** [comment]
Closing it now :)
