### ISSUE TITLE
[ADD] encom.eu.org

### ISSUE THREAD

**Issue by encombhat** [Atreatis/matrix-servers#5]
**Server name:** ENCOM
**Domain:** https://encom.eu.org
**Maintainer:** @bhat:encom.eu.org
**Support:** #status:encom.eu.org
**Founded:** May 28, 2018
**Web client:** None. [Riot.im](https://riot.im/app) works just fine. Duh.
**Description:** A general purpose Matrix homeserver hosted in Los Angeles, CA. It is intended to be an alternative method for circumventing Internet censorship in certain states and promote the free spread of knowledge. No reCAPTCHA or email verification required.

**Comment by Atreatis** [comment]
Added to the list + Website  👍
