### ISSUE TITLE
[ADD]

### ISSUE THREAD

**Issue by f0x52** [Atreatis/matrix-servers#6]
**Server name:**  Pixietown
**Domain:**  pixie.town
**Maintainer:**  [@f0x:pixie.town](https://matrix.to/#/@f0x:pixie.town)
**Founded:**  May 31st 2019
**Web client:**  https://neo.pixie.town/app
**Description:** Semi-public Matrix server part of the https://pixie.town services. For an account contact [f0x](https://matrix.to/#/@f0x:pixie.town) or email f at 0x52 dot eu

**Comment by Atreatis** [comment]
Added ✨
